#let _input-syntax-theme = bytes((
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
  "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">",
  "<plist version=\"1.0\">",
  "<dict>",
  "  <key>name</key>",
  "  <string>Calepin HTML Syntax Sentinel</string>",
  "  <key>settings</key>",
  "  <array>",
  "    <dict>",
  "      <key>settings</key>",
  "      <dict>",
  "        <key>foreground</key>",
  "        <string>#000000</string>",
  "      </dict>",
  "    </dict>",
  "    <dict>",
  "      <key>name</key>",
  "      <string>Function calls</string>",
  "      <key>scope</key>",
  "      <string>entity.name.function, support.function, variable.function</string>",
  "      <key>settings</key>",
  "      <dict>",
  "        <key>foreground</key>",
  "        <string>#000001</string>",
  "      </dict>",
  "    </dict>",
  "    <dict>",
  "      <key>name</key>",
  "      <string>Numeric literals</string>",
  "      <key>scope</key>",
  "      <string>constant.numeric</string>",
  "      <key>settings</key>",
  "      <dict>",
  "        <key>foreground</key>",
  "        <string>#000002</string>",
  "      </dict>",
  "    </dict>",
  "    <dict>",
  "      <key>name</key>",
  "      <string>Operators and special characters</string>",
  "      <key>scope</key>",
  "      <string>keyword.operator, punctuation.definition, punctuation.separator</string>",
  "      <key>settings</key>",
  "      <dict>",
  "        <key>foreground</key>",
  "        <string>#000003</string>",
  "      </dict>",
  "    </dict>",
  "    <dict>",
  "      <key>name</key>",
  "      <string>Assignments</string>",
  "      <key>scope</key>",
  "      <string>keyword.operator.assignment</string>",
  "      <key>settings</key>",
  "      <dict>",
  "        <key>foreground</key>",
  "        <string>#000004</string>",
  "      </dict>",
  "    </dict>",
  "    <dict>",
  "      <key>name</key>",
  "      <string>Named arguments</string>",
  "      <key>scope</key>",
  "      <string>variable.parameter, entity.other.attribute-name, support.variable.parameter</string>",
  "      <key>settings</key>",
  "      <dict>",
  "        <key>foreground</key>",
  "        <string>#000005</string>",
  "      </dict>",
  "    </dict>",
  "    <dict>",
  "      <key>name</key>",
  "      <string>Output emphasis</string>",
  "      <key>scope</key>",
  "      <string>markup.strong</string>",
  "      <key>settings</key>",
  "      <dict>",
  "        <key>foreground</key>",
  "        <string>#000006</string>",
  "      </dict>",
  "    </dict>",
  "  </array>",
  "</dict>",
  "</plist>",
).join("\n"))

#let _output-syntax-theme = _input-syntax-theme

#let _paged-syntax-theme = bytes((
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
  "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">",
  "<plist version=\"1.0\">",
  "<dict>",
  "  <key>name</key>",
  "  <string>Calepin Paged Syntax</string>",
  "  <key>settings</key>",
  "  <array>",
  "    <dict>",
  "      <key>settings</key>",
  "      <dict>",
  "        <key>foreground</key>",
  "        <string>#003b4f</string>",
  "        <key>background</key>",
  "        <string>#f7f7f5</string>",
  "      </dict>",
  "    </dict>",
  "    <dict>",
  "      <key>name</key>",
  "      <string>Function calls</string>",
  "      <key>scope</key>",
  "      <string>entity.name.function, support.function, variable.function</string>",
  "      <key>settings</key>",
  "      <dict>",
  "        <key>foreground</key>",
  "        <string>#4759ab</string>",
  "      </dict>",
  "    </dict>",
  "    <dict>",
  "      <key>name</key>",
  "      <string>Numeric literals</string>",
  "      <key>scope</key>",
  "      <string>constant.numeric</string>",
  "      <key>settings</key>",
  "      <dict>",
  "        <key>foreground</key>",
  "        <string>#ad0000</string>",
  "      </dict>",
  "    </dict>",
  "    <dict>",
  "      <key>name</key>",
  "      <string>Operators and special characters</string>",
  "      <key>scope</key>",
  "      <string>keyword.operator, punctuation.definition, punctuation.separator</string>",
  "      <key>settings</key>",
  "      <dict>",
  "        <key>foreground</key>",
  "        <string>#5e5e5e</string>",
  "      </dict>",
  "    </dict>",
  "    <dict>",
  "      <key>name</key>",
  "      <string>Assignments</string>",
  "      <key>scope</key>",
  "      <string>keyword.operator.assignment</string>",
  "      <key>settings</key>",
  "      <dict>",
  "      </dict>",
  "    </dict>",
  "    <dict>",
  "      <key>name</key>",
  "      <string>Named arguments</string>",
  "      <key>scope</key>",
  "      <string>variable.parameter, entity.other.attribute-name, support.variable.parameter</string>",
  "      <key>settings</key>",
  "      <dict>",
  "        <key>foreground</key>",
  "        <string>#667321</string>",
  "      </dict>",
  "    </dict>",
  "    <dict>",
  "      <key>name</key>",
  "      <string>Output emphasis</string>",
  "      <key>scope</key>",
  "      <string>markup.strong</string>",
  "      <key>settings</key>",
  "      <dict>",
  "        <key>fontStyle</key>",
  "        <string>bold</string>",
  "      </dict>",
  "    </dict>",
  "  </array>",
  "</dict>",
  "</plist>",
).join("\n"))

