//! The single authority for widget identity and rendering.
//!
//! Phase 1 gave every family the same `view` entry point. This module gives
//! every [`WidgetKind`] a stable, dotted [`WidgetId`] and a rendering
//! dispatch, so adding a widget is a fixed, small set of touches rather than
//! a `WidgetKind` match scattered across the crate.
//!
//! ## The generic-`Message` problem
//!
//! Every family's `view` is generic over `Message` (the application's
//! event type), and a `static` cannot hold a generic function pointer — Rust
//! has no way to store `for<Message> fn(...) -> Element<Message>` as a
//! value. [`dispatch`] is instead a single generic function, fed by a fixed
//! per-kind match generated by [`widget_registry!`] so the family match
//! lives in exactly one place; `layout_renderer::widget` calls it instead of
//! matching on `Family` itself.
//!
//! This is option (a) from the widget-host refactor plan: no boxing, no
//! `dyn Element` trees.
//!
//! Everything that is *data* rather than dispatch — label, tooltip, group,
//! capabilities, minimum size, and the frame [`super::plan`] a kind needs —
//! lives once in [`catalog::CATALOG`] (§81: it used to be split across a
//! second table here, `REGISTRY`, which held exactly the same shape of
//! per-kind fact and nothing this module needed that catalog data for).
//!
//! ## Adding a widget
//!
//! `pulpit.status.blank` (`widgets/status/blank.rs`, `WidgetKind::BlankSpace`)
//! is a living example — a static, decorative spacer with no configuration
//! and no capabilities. Copy its shape. Wiring a new kind touches:
//!
//! 1. **`widgets/mod.rs`** — add the `WidgetKind` variant, one line in
//!    `WidgetKind::ALL`, one arm in `WidgetKind::family()`, and one arm in
//!    `WidgetConfig::default_for` (join the `WidgetConfig::None` group
//!    unless the widget needs its own configuration shape).
//! 2. **`widgets/catalog.rs`** — one `WidgetDefinition` in `CATALOG`, kept in
//!    its group's run (the sidebar-order test enforces this). Its `plan`
//!    field says what frames it needs (`plan::none` unless it needs frames
//!    rendered) and its `thumbnail` field says what a layout thumbnail
//!    sketches for it — see [`catalog::ThumbnailContent`] — so
//!    `layout::thumbnail` needs no change.
//! 3. **`widgets/<family>/mod.rs`** and a new module (or an existing one) —
//!    the widget's own view code, and whatever pure model it needs.
//! 4. **`widgets/<family>/view.rs`** — one arm in that family's `view`
//!    dispatching to the new module. This is the one `match WidgetKind`
//!    site the source-scan test below allows per family, by design: within
//!    a family, choosing among its own kinds is that family's business.
//! 5. **This module's `widget_registry!` invocation** — one line: kind, its
//!    stable dotted id, and its family's `view`.
//!
//! Five touches, all inside `widgets/`, none of them a new central `match`.
//! `WidgetKind::ALL`'s length and the tests below fail loudly if a step is
//! skipped.

use super::view_context::WidgetViewContext;
use super::{Widget, WidgetKind};
use iced::Element;

/// A stable, dotted identity for a widget kind.
///
/// Distinct from [`WidgetKind`]'s Rust-side name: this is the identity a
/// persisted layout refers to (`layout::store`'s `widget_id` field), so
/// renaming a Rust variant does not have to mean rewriting every saved file.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct WidgetId(pub &'static str);

impl WidgetId {
    // Used by the tests below; `layout::store`'s import/export path is the
    // application caller, through `WidgetKind::id`/`from_id` rather than
    // this directly.
    #[allow(dead_code)]
    pub const fn as_str(self) -> &'static str {
        self.0
    }
}

impl std::fmt::Display for WidgetId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.0)
    }
}

/// Declares the `WidgetKind -> WidgetId` mapping, the reverse lookup and the
/// render dispatch from one list, so a new widget touches this macro
/// invocation and nothing else in this module.
macro_rules! widget_registry {
    ( $( $kind:ident => $id:literal => $view:path ),+ $(,)? ) => {
        impl WidgetKind {
            /// This kind's stable, dotted identity.
            pub fn id(self) -> WidgetId {
                match self {
                    $( WidgetKind::$kind => WidgetId($id), )+
                }
            }

            /// The kind that owns an id, if any is registered under it.
            pub fn from_id(id: &str) -> Option<WidgetKind> {
                match id {
                    $( $id => Some(WidgetKind::$kind), )+
                    _ => None,
                }
            }
        }

        /// Render one widget through its family's uniform entry point.
        ///
        /// The only place in the crate that matches on `WidgetKind` (rather
        /// than `Family`) to choose a renderer; [`crate::layout_renderer`]
        /// calls this instead of matching on `Family` itself.
        pub fn dispatch<'ctx, 'a, Message: Clone + 'static>(
            ctx: &WidgetViewContext<'ctx, 'a, Message>,
            widget: &Widget,
        ) -> Element<'a, Message> {
            match widget.kind() {
                $( WidgetKind::$kind => $view(ctx, widget), )+
            }
        }

        /// Render one kind using a host cell's common style. Side-panel
        /// infrastructure uses this when a transient widget occupies a
        /// persistent panel slot.
        pub fn dispatch_kind<'ctx, 'a, Message: Clone + 'static>(
            kind: WidgetKind,
            ctx: &WidgetViewContext<'ctx, 'a, Message>,
            host: &Widget,
        ) -> Element<'a, Message> {
            match kind {
                $( WidgetKind::$kind => $view(ctx, host), )+
            }
        }
    };
}

widget_registry! {
    CurrentSlide         => "pulpit.slide.current"             => super::slides::view::view,
    PreviousSlide        => "pulpit.slide.previous"            => super::slides::view::view,
    NextSlide             => "pulpit.slide.next"                => super::slides::view::view,
    PreviousCurrentNext  => "pulpit.slide.previous-current-next" => super::slides::view::view,
    SpeakerNotes          => "pulpit.notes.speaker"             => super::notes::view::view,
    Timer                 => "pulpit.timer.elapsed"             => super::timing::view::view,
    Clock                 => "pulpit.timer.clock"               => super::timing::view::view,
    SlideButtons          => "pulpit.navigation.buttons"        => super::navigation::view::view,
    SlideSlider           => "pulpit.navigation.slider"         => super::navigation::view::view,
    SlideCounter          => "pulpit.navigation.counter"        => super::navigation::view::view,
    PauseResume           => "pulpit.navigation.pause-resume"   => super::navigation::view::view,
    EndPresentation       => "pulpit.navigation.end"            => super::navigation::view::view,
    PresentationTitle     => "pulpit.status.title"              => super::status::view::view,
    CurrentSection        => "pulpit.status.section"            => super::status::view::view,
    AudienceScreenStatus  => "pulpit.status.audience-screen"    => super::status::view::view,
    ConnectionStatus      => "pulpit.status.connection"         => super::status::view::view,
    Annotations           => "pulpit.annotations.palette"       => super::annotations::view::view,
    MediaTransport        => "pulpit.media.transport"           => super::media::view::view,
    MainMenu              => "pulpit.chrome.main-menu"          => super::chrome::view::view,
    AudienceControls      => "pulpit.chrome.audience-controls"  => super::chrome::view::view,
    DocumentPage          => "pulpit.document.page"             => super::document::view::view,
    DocumentNav           => "pulpit.document.nav"              => super::document::view::view,
    DocumentOutline       => "pulpit.document.outline"          => super::document::view::view,
    AnnotationTools       => "pulpit.document.annotation-tools" => super::document::view::view,
    Search                => "pulpit.search.query"              => super::search::view::view,
    BlankSpace            => "pulpit.status.blank"               => super::status::view::view,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_id_is_unique_dotted_and_lowercase() {
        let mut seen = std::collections::HashSet::new();
        for kind in WidgetKind::ALL {
            let id = kind.id().as_str();
            assert!(id.contains('.'), "{id:?} for {kind:?} is not dotted");
            assert_eq!(
                id,
                id.to_lowercase(),
                "{id:?} for {kind:?} is not lowercase"
            );
            assert!(
                id.chars()
                    .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '.' || c == '-'),
                "{id:?} for {kind:?} has an unexpected character",
            );
            assert!(
                seen.insert(id),
                "{id:?} is registered more than once ({kind:?})"
            );
        }
    }

    #[test]
    fn every_id_round_trips_through_the_reverse_lookup() {
        for kind in WidgetKind::ALL {
            assert_eq!(WidgetKind::from_id(kind.id().as_str()), Some(kind));
        }
        assert_eq!(WidgetKind::from_id("not.a.real.id"), None);
    }

    #[test]
    fn dispatch_draws_every_kind() {
        // Exercises the generated match; a kind missing from the macro list
        // would be a compile error (non-exhaustive match), so this mainly
        // proves the function actually returns rather than panicking.
        let context = super::super::sample::context(crate::widgets::context::Mode::Live);
        let ctx: WidgetViewContext<'_, '_, ()> =
            WidgetViewContext::new(&context, None, |_| (), 1.0);
        for kind in WidgetKind::ALL {
            let widget = Widget::new(kind);
            let _: Element<'_, ()> = dispatch(&ctx, &widget);
        }
    }

    /// The architectural gate: outside a widget's own family (or this
    /// module and `plan.rs`, which *are* the registry), a `match` on
    /// `WidgetKind` or `Family` is exactly the scattering this refactor
    /// closed off. A new central dispatch point is a regression, not a
    /// style choice, so this fails the build rather than waiting for review.
    ///
    /// Deliberately simple: a source-text scan for the handful of literal
    /// patterns every real dispatch site in this crate happens to use, over
    /// each file's text up to its first `#[cfg(test)]` (test-only reference
    /// implementations, e.g. `layout::builtin`'s and `layout::panels`'
    /// pre-refactor comparison walks, are not the scattering this guards
    /// against). Good enough to catch a new one being added; not a Rust
    /// parser, and not trying to be.
    #[test]
    fn widgetkind_and_family_matches_stay_where_they_belong() {
        // Files where a `match` on `WidgetKind`/`Family` is the point of the
        // file, not a leak: this module and `plan.rs` generate/hold the
        // per-kind dispatch tables; `widgets/mod.rs` is the vocabulary
        // itself (`family()`, `WidgetConfig::default_for`, and two small
        // configuration reads); each family's own `view.rs` chooses among
        // its own kinds, which is that family's business, not the host's.
        const ALLOWED: &[&str] = &[
            "widgets/mod.rs",
            "widgets/registry.rs",
            "widgets/plan.rs",
            "widgets/slides/view.rs",
            "widgets/notes/view.rs",
            "widgets/timing/view.rs",
            "widgets/navigation/view.rs",
            "widgets/status/view.rs",
            "widgets/annotations/view.rs",
            "widgets/media/view.rs",
            "widgets/chrome/view.rs",
            "widgets/document/view.rs",
            "widgets/search/view.rs",
        ];
        const PATTERNS: &[&str] = &[
            "match widget.kind()",
            "match kind {",
            "match self.kind {",
            "match self.kind.family()",
        ];

        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
        let mut offenders = Vec::new();
        visit(&root, &root, ALLOWED, PATTERNS, &mut offenders);
        assert!(
            offenders.is_empty(),
            "match over WidgetKind/Family found outside the allowlist: {offenders:?}\n\
             Either move the dispatch into a family module, drive it from \
             registry/catalog data, or add the file to ALLOWED with a reason."
        );

        fn visit(
            dir: &std::path::Path,
            root: &std::path::Path,
            allowed: &[&str],
            patterns: &[&str],
            offenders: &mut Vec<String>,
        ) {
            for entry in std::fs::read_dir(dir).expect("readable src tree") {
                let path = entry.expect("readable dir entry").path();
                if path.is_dir() {
                    visit(&path, root, allowed, patterns, offenders);
                    continue;
                }
                if path.extension().is_none_or(|ext| ext != "rs") {
                    continue;
                }
                let relative = path
                    .strip_prefix(root)
                    .unwrap()
                    .to_string_lossy()
                    .replace(std::path::MAIN_SEPARATOR, "/");
                if allowed.contains(&relative.as_str()) {
                    continue;
                }
                let text = std::fs::read_to_string(&path).expect("readable source file");
                let production = text.split("#[cfg(test)]").next().unwrap_or(&text);
                for pattern in patterns {
                    for (start, _) in production.match_indices(pattern) {
                        // A `match kind {`/`match widget.kind() {` header
                        // names no type; confirm this one is actually a
                        // `WidgetKind`/`Family` match, not some other
                        // `kind`-named enum (`ContentKind`, `AppliedKind`,
                        // `FrameKind`, ...), by checking its arms name one.
                        let window_end = (start + 400).min(production.len());
                        let window = &production[start..window_end];
                        if window.contains("WidgetKind::") || window.contains("Family::") {
                            offenders.push(format!("{relative}: {pattern:?}"));
                            break;
                        }
                    }
                }
            }
        }
    }
}
