title = "Pulpit"
description = "A focused PDF presenter in Rust that does not screw up your projector."
base-url = "https://vincentarelbundock.github.io/pulpit"
theme = "calepin"
logo = "assets/logo.svg"
logo-alt = "Pulpit"
favicon = "assets/favicon.svg"

pdf = true

[static]
include = ["assets/**"]

[[menus.main]]
target = "install.typ"
label = "Documentation"

[[menus.social]]
target = "https://github.com/vincentarelbundock/pulpit"
label = "{icon:github}"
aria-label = "GitHub"

[footer]

  [[footer.item]]
  label = "MIT or Apache-2.0"

  [[footer.item]]
  target = "https://vincentarelbundock.github.io/calepin"
  label = "Made with Calepin"

[sidebar]
fold = false

[[sidebar.section]]
title = "Pulpit"

  [[sidebar.section.item]]
  target = "index.typ"

  [[sidebar.section.item]]
  target = "install.typ"

  [[sidebar.section.item]]
  target = "usage.typ"

  [[sidebar.section.item]]
  target = "internals.typ"
