title = "Pulpit"
description = "A focused PDF presenter in Rust that does not screw up your projector."
base-url = "https://vincentarelbundock.github.io/pulpit"
theme = "themes/pulpit"
logo = "assets/logo.svg"
logo-alt = "Pulpit"
favicon = "assets/favicon.svg"

pdf = false

[toc]
enabled = true
depth = 3

[static]
include = ["assets/**"]

[pages]
exclude = ["parts/*.typ", "internals.typ"]

[[menus.social]]
target = "https://github.com/vincentarelbundock/pulpit"
label = "{icon:github}"
aria-label = "GitHub"

[footer]

  [[footer.item]]
  label = "MIT or Apache-2.0"

  [[footer.item]]
  target = "https://vincentarelbundock.github.io/calepin"
  label = "Made with Calepin"
