// Generated from the application keymap. Do not edit.
//
// Regenerate with `make docs-keys` after changing
// `crates/pulpit/src/settings/keys.rs`.

#table(
  columns: (auto, 1fr, auto, 1fr),
  stroke: none,
  inset: (x: 0.5em, y: 0.4em),
  table.cell(colspan: 4)[#smallcaps[Files & application]],
  [`Ctrl+O`], [Open…], [`Ctrl+R`], [Reload document],
  [`Ctrl+P`], [Print…], [`L`], [Next layout],
  [`Shift+L`], [Layouts], [`Shift+/`], [Keyboard shortcuts],
  [`Ctrl+Q`], [Quit], [], [],
  table.cell(colspan: 4)[#smallcaps[Move through pages]],
  [`→` `PgDn` (`J`)], [Next page], [`←` `PgUp` (`K`)], [Previous page],
  [`Home`], [First page], [`End` (`Shift+G`)], [Last page],
  [`O`], [Page overview], [`P`], [Autoadvance],
  table.cell(colspan: 4)[#smallcaps[Present]],
  [`B`], [Blank], [`T`], [Start/pause timer],
  [`Shift+T`], [Reset timer], [`S`], [Swap displays],
  [`F`], [Audience fullscreen], [], [],
  table.cell(colspan: 4)[#smallcaps[Read aloud]],
  [`R`], [Read the document aloud / pause], [`Shift+R`], [Read page or selection aloud / pause],
  [`Shift+→`], [Next sentence], [`Shift+←`], [Previous sentence],
  table.cell(colspan: 4)[#smallcaps[Annotate]],
  [`1`], [Hold marks with a rubber band], [`2`], [Draw on the page],
  [`3`], [Highlight on the page], [`4`], [Write on the page],
  [`5`], [Leave a note on the page], [`6`], [Erase annotations],
  [`7`], [Point at the page], [`8`], [Select text on the page],
  [`Ctrl+C`], [Copy the selected text], [`Ctrl+Z` (`U`)], [Undo the last stroke],
  [`Ctrl+Shift+Z`], [Redo the last stroke], [`C`], [Clear annotations],
  [`V`], [Show annotations to the audience], [], [],
  table.cell(colspan: 4)[#smallcaps[Read & search]],
  [`Ctrl+B`], [Show or hide the bookmarks], [`Ctrl+F` (`/`)], [Search],
  [`F3` (`N`)], [Next match], [`Shift+F3` (`Shift+N`)], [Previous match],
  table.cell(colspan: 4)[#smallcaps[Page view]],
  [`Ctrl+=` (`+`)], [Zoom in], [`Ctrl+-` (`-`)], [Zoom out],
  [`Ctrl+1` (`=`)], [Actual size], [`Ctrl+0` (`A`)], [Fit page],
  [`Ctrl+2`], [Fit width], [`Ctrl+Shift+R`], [Rotate pages],
  [`D`], [Toggle two-page view], [`I`], [Page colours],
)
